---
title: "Shark_RDA"
output: pdf_document
---

##RDA; Redundancy Analysis

since I am working with multivariate data (14 response landmarks each with their own x/y coordinates), would like to extract those gradients of variation in tooth shape (landmarks) expalinable by the independent variables (tooth position, individual, species, and jaw type)
The RDA serves the purpose of a MANOVA for my dataset .

#What is the effect of species, jaw type, and tooth position on overall variation?

```{r}

#run an RDA to look at variance partitioning

all_rda <- rda(coords ~ sharkdat$species + as.factor(sharkdat$jaw.type) +
                 as.factor(sharkdat$tooth.position))

#after looking at several RDA's (looking at interactions and inclusion of #individuals) , this RDA outputs the most variance explained by the #independent variables. 

anova(all_rda, permutations = 1000)
anova(all_rda, by="margin")

#output shows that jaw type accounts for a significant amount of variation, followed 
#by species and then tooth position. 


RsquareAdj(all_rda)

#variance explained by the RDA is about 58%. This is fairly good. 

plot(all_rda, type='n', scaling=1)
orditorp(all_rda, display='sp', cex=0.5, scaling=1, col='blue')
text(all_rda, display='bp', col='red')

#VarPart for Variance Partitioning

sp_dum = dummy(sharkdat$species)
jaw_dum = dummy(sharkdat$jaw.type)
pos_dum = dummy(sharkdat$tooth.position)

varpart(coords, sp_dum, jaw_dum, pos_dum)
showvarparts(3)


#this is saying that the jaw explains about 30% of the variance, tooth position
#explains 18% of the variance, and species only 7%. Since these 3 species #are 
#closely related in the genus Carcharhinus, they show little #differentiation. 
#The upper and lower jaws show the most amount of variance, since they have
#different functions, as well as the tooth position. 


```

The RDA allows us to see what predictor variables account for variation
but for a visual, let's analyze the distribution of raw data in a PCA; see if there is an emphasis in variation among the individual samples by gradients of the total sample variance. Visually Analyze structure of distribution of sample variance 
